language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  exclude:
    - php: 5.3
      env: TYPO3_VERSION=dev-master
    - php: 5.4
      env: TYPO3_VERSION=dev-master

env:
  - TYPO3_VERSION=dev-master
  - TYPO3_VERSION=6.2.*@dev

notifications:
  email:
    - helmut@typo3.org

before_script:
  - sudo apt-get install parallel
  - composer self-update
  - cd ..
  - composer create-project --no-interaction typo3/cms-base-distribution=$TYPO3_VERSION typo3_core
  - mv typo3_core/* .
  - mkdir -p typo3conf/ext/
  - mv typoscript_rendering typo3conf/ext/

script:
  - >
    echo;
    echo "Running unit tests";
    ./bin/phpunit --colors -c typo3/sysext/core/Build/UnitTests.xml typo3conf/ext/typoscript_rendering/Tests/Unit/
  - >
    echo;
    echo "Running php lint";
    /bin/bash -c "
        if ! find typo3conf/ext/typoscript_rendering -name \*.php | parallel --gnu 'php -l {}' > /tmp/errors 2>&1; then
            grep -v \"No syntax errors detected in\" /tmp/errors;
            exit 99;
        fi
    "
